language: php

php:
  - 5.5
  - 5.6

script:
  - composer install
  - composer require codeclimate/php-test-reporter --dev
  - phpunit

after_success:
  - CODECLIMATE_REPO_TOKEN="1507d64611936916afbb6b259368bde16d39a733032a95f7e52c2a4c271f279d" vendor/bin/test-reporter
